services:
  AwesomeProject\AwesomeProjectApplication:
    public: true

  AwesomeProject\:
    resource: 'src/{Aggregator,Command,Manager,Console}'
    public: true
    autowire: true

  AwesomeProject\Command\:
    resource: 'src/Command'
    autowire: true
    tags: [ 'command' ]
    calls:
      - [ 'setProjectSummaryRenderer',[ '@AwesomeProject\Console\Renderer\ProjectSummaryRenderer' ] ]
      - [ 'setDockerComposeManager',[ '@AwesomeProject\Manager\DockerComposeManager' ] ]

  AwesomeProject\Factory\ManifestFactory:
    arguments:
      $serializer: '@JMS\Serializer\Serializer'

  AwesomeProject\Factory\RootProjectFactory:
    arguments:
      $manifest: '@AwesomeProject\Model\Manifest\MainManifest'

  AwesomeProject\Model\Manifest\MainManifest:
    factory: [ '@AwesomeProject\Factory\ManifestFactory','getMainManifest' ]
    public: true

  AwesomeProject\Model\RootProject:
    factory: [ '@AwesomeProject\Factory\RootProjectFactory','createRootProject' ]
    public: true

  JMS\Serializer\Serializer:
    factory: 'AwesomeProject\Serializer\SerializerBuilder::create'
